version: "3.7"

services:
  gpt-2:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - gpt-2-cpu
    image: gpt-2

  gpt-2-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    image: gpt-2-cpu

  interactive:
    command: src/interactive_conditional_samples.py --top_k 40
    depends_on:
      - gpt-2
    entrypoint: python3
    image: gpt-2
